### ISSUE TITLE
gnuradio 3.10 support

### ISSUE THREAD

**Issue by ra1nb0w** [daniestevez/gr-linrad#3]
Hi,
do you have the idea to update gr-linrad to gnuradio 3.10?
thank you

**Comment by daniestevez** [comment]
I had no plans of updating this OOT, since I use it infrequently (and still have GR 3.8 around for that). It's a simple OOT, so if there's interest I could update it within the next few weeks.

Something else that I (or someone else) should look into is whether this works with the latests versions of Linrad. I overheard that there are some changes in the network protocol. I'm still using Linrad 04.14.

**Comment by ra1nb0w** [comment]
Thank you for the answer.
The request was born from the update to gnuradio 3.10 on macports (macOS package manager). Probably not many use this OOT so I don't know if it is worth your time.
About the network protocol: I used gr-linrad a bit in the past with linrad 5.01 and if I remember correctly was working fine.

**Comment by daniestevez** [comment]
I've updated the main branch to add support for GNU Radio 3.9. I think this should also build and work with GNU Radio 3.10, but  I haven't tested it.

**Comment by ra1nb0w** [comment]
thank you very much.
Building I get the following error:
```
-- Found pybind11: /opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pybind11/include (found version "2.9.2")
Traceback (most recent call last):
  File "/Users/rainbow/tmp/gr-linrad/python/bindings/header_utils.py", line 67, in <module>
    pbhp = PybindHeaderParser(args.pathname)
  File "/Users/rainbow/tmp/gr-linrad/python/bindings/header_utils.py", line 9, in __init__
    with open(pathname,'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rainbow/tmp/gr-linrad/python/bindings/send_raw16_python.cc'
CMake Error at /opt/local/share/cmake/gnuradio/GrPybind.cmake:198 (list):
  list GET given empty list
Call Stack (most recent call first):
  python/bindings/CMakeLists.txt:36 (GR_PYBIND_MAKE_OOT)


CMake Error at /opt/local/share/cmake/gnuradio/GrPybind.cmake:199 (list):
  list GET given empty list
Call Stack (most recent call first):
  python/bindings/CMakeLists.txt:36 (GR_PYBIND_MAKE_OOT)


CMake Error at /opt/local/share/cmake/gnuradio/GrPybind.cmake:200 (list):
  list GET given empty list
Call Stack (most recent call first):
  python/bindings/CMakeLists.txt:36 (GR_PYBIND_MAKE_OOT)


CMake Error at /opt/local/share/cmake/gnuradio/GrPybind.cmake:201 (list):
  list GET given empty list
Call Stack (most recent call first):
  python/bindings/CMakeLists.txt:36 (GR_PYBIND_MAKE_OOT)


Traceback (most recent call last):
  File "/Users/rainbow/tmp/gr-linrad/python/bindings/header_utils.py", line 67, in <module>
    pbhp = PybindHeaderParser(args.pathname)
  File "/Users/rainbow/tmp/gr-linrad/python/bindings/header_utils.py", line 9, in __init__
    with open(pathname,'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/rainbow/tmp/gr-linrad/python/bindings/send_raw24_python.cc'
CMake Error at /opt/local/share/cmake/gnuradio/GrPybind.cmake:198 (list):
  list GET given empty list
Call Stack (most recent call first):
  python/bindings/CMakeLists.txt:36 (GR_PYBIND_MAKE_OOT)


CMake Error at /opt/local/share/cmake/gnuradio/GrPybind.cmake:199 (list):
  list GET given empty list
Call Stack (most recent call first):
  python/bindings/CMakeLists.txt:36 (GR_PYBIND_MAKE_OOT)


CMake Error at /opt/local/share/cmake/gnuradio/GrPybind.cmake:200 (list):
  list GET given empty list
Call Stack (most recent call first):
  python/bindings/CMakeLists.txt:36 (GR_PYBIND_MAKE_OOT)


CMake Error at /opt/local/share/cmake/gnuradio/GrPybind.cmake:201 (list):
  list GET given empty list
Call Stack (most recent call first):
  python/bindings/CMakeLists.txt:36 (GR_PYBIND_MAKE_OOT)


-- Configuring incomplete, errors occurred!
```

**Comment by daniestevez** [comment]
Sorry, I forgot to add some files to the repo. I've added them now.

**Comment by ra1nb0w** [comment]
it is working fine now. Thank you very much!
Have a great weekend
